# Offensive Language Classification

In [1]:
import pandas as pd
import numpy as np

In [2]:
# check if we have a GPU
!nvidia-smi

Fri Sep  4 16:02:47 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 610.57.04              KMD Version: 610.57.04     CUDA UMD Version: 13.3     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5090        On  |   00000000:21:00.0 Off |                  N/A |
|  0%   51C    P8             14W /  575W |   31963MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 5090        On  |   00000000:C1:00.0 Off |                  N/A |
| 48%   60C    P1            264W /  575W |   12720MiB /  32607MiB |     36%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A          432899      C   ...-ki-deepdive/.venv/bin/python      31314MiB |
|    0   N/A  N/A          449366      C   ...-ki-deepdive/.venv/bin/python        630MiB |
|    1   N/A  N/A          456239      C   ...e/kim_reset/.venv/bin/python3      12698MiB |
+-----------------------------------------------------------------------------------------+

## Prepairing the data

In the next step we have to load the data and adjust it a bit. The data is available in tab delimited csv. Pandas is a good choice for simple processing, but it could also be done with Python board tools.

In [3]:
test_df = pd.read_csv("./data/germeval2018.test.txt", sep='\t', header=0,encoding="utf-8")
train_df = pd.read_csv("./data/germeval2018.train.txt", sep='\t', header=0,encoding="utf-8")

In [4]:
train_df.head()

                                                text    label  label2
0  @corinnamilborn Liebe Corinna, wir würden dich...    OTHER   OTHER
1  @Martin28a Sie haben ja auch Recht. Unser Twee...    OTHER   OTHER
2  @ahrens_theo fröhlicher gruß aus der schönsten...    OTHER   OTHER
3  @dushanwegner Amis hätten alles und jeden gewä...    OTHER   OTHER
4  @spdde kein verläßlicher Verhandlungspartner. ...  OFFENSE  INSULT

In [5]:
# Since we do not need the label 2 columns, we can delete them.
test_df.drop(columns=['label2'], inplace=True)
train_df.drop(columns=['label2'], inplace=True)

In [6]:
def clean_text (text):
    #text = text.str.lower() # lowercase
    #text = text.str.replace(r"\#","") # replaces hashtags
    #text = text.str.replace(r"http\S+","URL")  # remove URL addresses
    #text = text.str.replace(r"@","")
    #text = text.str.replace(r"[^A-Za-z0-9öäüÖÄÜß()!?]", " ")
    #text = text.str.replace("\s{2,}", " ")
    return text

def convert_label(label):
    return 1 if label == "OFFENSE" else 0

In [7]:
train_df["text"]=clean_text(train_df["text"])
test_df["text"]=clean_text(test_df["text"])
train_df["label"]=train_df["label"].map(convert_label)
test_df["label"]=test_df["label"].map(convert_label)

In [8]:
# this is  how our data set looks now
train_df.head()

                                                text  label
0  @corinnamilborn Liebe Corinna, wir würden dich...      0
1  @Martin28a Sie haben ja auch Recht. Unser Twee...      0
2  @ahrens_theo fröhlicher gruß aus der schönsten...      0
3  @dushanwegner Amis hätten alles und jeden gewä...      0
4  @spdde kein verläßlicher Verhandlungspartner. ...      1

In [9]:
len(train_df.loc[train_df["label"]==1])

1688

In [10]:
from sklearn.utils import shuffle
train_df = shuffle(train_df)

How many datasets do we have in our Train/Valid/Test sets?

In [11]:
print(f"Test exampels \t {len(test_df) }")
print(f"Train exampels \t {len(train_df[500:])}")
print(f"Valid exampels \t {len(train_df[:500])}")

Test exampels 	 3398
Train exampels 	 4509
Valid exampels 	 500

In the next step we convert the data in a format that our ml lib can use.

In [12]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

/home/ogu/source/workshop-ki-deepdive/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
# What is the shape of our dataset?
train_dataset

Dataset({
    features: ['text', 'label', '__index_level_0__'],
    num_rows: 5009
})

## Encoding of the data 

We convert our texts into token that our model can process.

In [14]:
from transformers import AutoTokenizer
from datasets import load_dataset


# try out different models :) 

model_checkpoint ="distilbert-base-multilingual-cased"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [15]:
!rm -rf ./test-offsive-language/checkpoint*

In [16]:
demo_tokens = tokenizer(["Mehr Daten führen oftmals zu besseren Ergebnissen.", "And this is a second sentence"],add_special_tokens=True, truncation=True)
demo_tokens

{'input_ids': [[101, 74658, 42635, 32092, 18496, 42488, 10304, 53978, 10136, 47419, 10115, 119, 102], [101, 12689, 10531, 10124, 169, 11132, 49219, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [17]:
tokenizer.convert_ids_to_tokens(demo_tokens['input_ids'][0])

['[CLS]',
 'Mehr',
 'Daten',
 'führen',
 'oft',
 '##mals',
 'zu',
 'besser',
 '##en',
 'Ergebnisse',
 '##n',
 '.',
 '[SEP]']

In [18]:
def example_tokenizer(examples):
    return tokenizer(examples["text"], truncation=True,padding=True)

In [19]:
encoded_train_dataset = train_dataset.map(example_tokenizer, batched=True)
encoded_test_dataset = test_dataset.map(example_tokenizer, batched=True)

Map: 100%|██████████| 5009/5009 [00:00<00:00, 21023.50 examples/s]
Map: 100%|██████████| 3398/3398 [00:00<00:00, 11159.38 examples/s]

## The training \o/

Now we can train our model. To do this, we need to define a number of settings (hyperparameters):

In [ ]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=2)

batch_size = 16

args = TrainingArguments(
    "test-offensive-language",
    eval_strategy="steps",
    save_strategy="steps",
    learning_rate=4e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size * 4,
    gradient_accumulation_steps=4,
    num_train_epochs=2,
    eval_steps=0.2,
    save_steps=0.2,
    warmup_steps=50,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    save_total_limit=2,
    bf16=True,
 )

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 22216.77it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-multilingual-cased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [22]:
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(pred):
  labels = pred.label_ids
  preds = pred.predictions.argmax(-1)
  f1 = f1_score(labels, preds, average="macro")
  acc = accuracy_score(labels, preds)
  return {"accuracy": acc, "f1": f1}

In [23]:
trainer = Trainer(
    model,
    args,
    train_dataset=encoded_train_dataset,
    eval_dataset=encoded_test_dataset,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
 )

In [24]:
trainer.train()

/home/ogu/source/workshop-ki-deepdive/.venv/lib/python3.14/site-packages/torch/nn/parallel/scatter_gather.py:130: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return Gather.apply(target_device, dim, *outputs)

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.02it/s]
/home/ogu/source/workshop-ki-deepdive/.venv/lib/python3.14/site-packages/torch/nn/parallel/scatter_gather.py:130: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return Gather.apply(target_device, dim, *outputs)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
/home/ogu/source/workshop-ki-deepdive/.venv/lib/python3.14/site-packages/torch/nn/parallel/scatter_gather.py:130: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return Gather.apply(target_device, dim, *outputs)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.28it/s]
/home/ogu/source/workshop-ki-deepdive/.venv/lib/python3.14/site-packages/torch/nn/parallel/scatter_gather.py:130: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return Gather.apply(target_device, dim, *outputs)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.23it/s]
/home/ogu/source/workshop-ki-deepdive/.venv/lib/python3.14/site-packages/torch/nn/parallel/scatter_gather.py:130: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return Gather.apply(target_device, dim, *outputs)
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.54it/s]

TrainOutput(global_step=80, training_loss=4.6391607284545895, metrics={'train_runtime': 62.6595, 'train_samples_per_second': 159.88, 'train_steps_per_second': 1.277, 'total_flos': 590939135207520.0, 'train_loss': 4.6391607284545895, 'epoch': 2.0})

In [ ]:
#tensorboard --logdir runs
%load_ext tensorboard
#%reload_ext tensorboard
%tensorboard --logdir /content/test-offsive-language/runs

## Testing the model

The next step is to test the model with the provided test data.

In [25]:
result = trainer.predict(encoded_test_dataset)
result.metrics["test_f1"]

/home/ogu/source/workshop-ki-deepdive/.venv/lib/python3.14/site-packages/torch/nn/parallel/scatter_gather.py:130: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return Gather.apply(target_device, dim, *outputs)

0.6451797058700234

In [26]:
import torch

#trainer.prediction_step(trainer.model,tokenizer("das ist ein test"),False)
trainer.model.cpu()
#trainer.model.num_parameters()
encoded_texts = tokenizer(["du bist so dumm", "du bist toll"],padding=True, return_tensors="pt")
print(encoded_texts)
logits = trainer.model(**encoded_texts)
probabilities = torch.softmax(logits[0],dim=1)
print(probabilities)
class_label = torch.argmax(probabilities,dim=1)
print(class_label)

{'input_ids': tensor([[  101, 10168, 10467, 10123, 10380, 54892, 10147,   102],
        [  101, 10168, 10467, 10123, 81754,   102,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0]])}
tensor([[0.8460, 0.1540],
        [0.8674, 0.1326]], grad_fn=<SoftmaxBackward0>)
tensor([0, 0])

How can we predict a sigle test example and how long does it take on a cpu?

In [27]:
def predict(text):
    trainer.model.cpu()
    #trainer.model.num_parameters()
    encoded_texts = tokenizer(text, return_tensors="pt")
    #print(encoded_texts)
    logits = trainer.model(**encoded_texts)
    probabilities = torch.softmax(logits[0],dim=1)
    #print(probabilities)
    class_label = torch.argmax(probabilities)
    return class_label
    #print(class_label)

%timeit predict("du bist so toll")

9.24 ms ± 524 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# Tutorial:

Our results are already quite good - but we can still improve the results.  First get familiar with the notebook - change a few parameters like learning rate and number of epochs and see how they change the results. 

**Your task is to improve the classification score.**

Here are some ideas how you can improve the score.

* Test different models. The [Model Hub](https://huggingface.co/models) lists a number of German models with which you can improve the results. 

* About 5000 sampels in the data set are comparatively few for this problem. You may find more data sets that you can add to the current training data set.

* A number of multilingual models are available in the [Model Hub](https://huggingface.co/models). These models have been trained with different languages. You could also try adding English to the German dataset to train a multilingual model. This may also be better on the German data. 

Data augmentation is a procedure to create new data sets by modifying existing data sets. It is important that the statement does not change (the class remains the same).

* You can replace synonyms words and thus generate new data sets. An example:

> "Can you still believe all this crap?" -> "Can you still believe all this crap?"

* Everything is allowed here. Try translating texts from German to English and back to German. If the meaning is preserved, the result can also be used for training. A small example with Google Translate:

> Deutsch: "Kann man diesen ganzen Scheiß noch glauben?" 

> Englisch: "Can you still believe all this shit?"

> Deutsch: "Kannst du all diese Scheiße noch glauben?"